theme: minima
title: Dane's Compendium
author: Taercy
email: dsacello@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is the small leatherbound notebook my brain would look like if everything I had ever done or thought about was a physical thing.
# social links
discord_username: Taercy#7277
github_username:  taercy # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
